version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - restore_cache:
          keys:
            - pip_cache-{{ checksum "requirements.txt" }}
            - pip_cache
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - save_cache:
          paths:
            - ~/.cache/pip
          key: pip_cache-{{ checksum "requirements.txt"}}
      - run:
          name: Run tests
          command: |
            mkdir test-results
            pytest --junitxml=test-results/junit.xml
      - store_test_results:
          path: test-results
      - run:
          name: Generate combined CSKG CSV
          command: |
            mkdir cskg
            python -m mowgli.cli --pipeline-module combined --data-dir-path cskg
      - run:
          name: Generate combined CSKG RDF (master branch only)
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              python3 -m mowgli.cli --pipeline-module rdf --nodes-csv-file-path cskg/combined/loaded/nodes.csv --edges-csv-file-path cskg/combined/loaded/edges.csv --pipeline-id combined-rdf
            fi
      - run:
          name: Archive artifacts
          command: |
            cd cskg
            for dir in `ls`; do
              mv "$dir/loaded/"*.csv "$dir/"
              rm -r "$dir/extracted" "$dir/transformed" "$dir/loaded"
            done
            cd ..
            tar -cvjSf cskg.tar.bz2 cskg
      - store_artifacts:
          path: cskg.tar.bz2
