version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - restore_cache:
          keys:
            - pip_cache-{{ checksum "requirements.txt" }}
            - pip_cache
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - save_cache:
          paths:
            - ~/.cache/pip
          key: pip_cache-{{ checksum "requirements.txt"}}
  test_python:
      - run:
          name: Run tests
          command: |
            mkdir test-results
            pytest --junitxml=test-results/junit.xml
      - store_test_results:
          path: test-results
  generate_cskg:
    steps:
      - run:
          name: Generate CSKG
          command: |
            mkdir cskg
            python -m mowgli.cli --pipeline-module combined --data-dir-path cskg
            tar -cvjSf cskg.tar.bz2 cskg
      - store_artifacts:
          path: cskg.tar.bz2

workflows:
  version: 2
  build:
    jobs:
      - build
      - test_python:
          requires:
            - build
      - generate_cskg:
          requires:
            - test_python
